---
- name: Add HipChat Repository
  become: yes
  apt_repository:
      repo: "deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client {{ansible_distribution_release}} main"
      update_cache: yes
      state: present
  when: atlassian_hipchat_install

- name: Install HipChat Package
  become: yes
  package:
      name: "{{item}}"
      state: present
      allow_unauthenticated: yes
  with_items:
  - "hipchat4"
  when: atlassian_hipchat_install

